name: datageo_sdk_build

services:

  postgis:
    container_name: postgis
    image: postgis/postgis:latest
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 5s
      retries: 5

  minio:
    container_name: minio
    image: bitnami/minio:latest
    environment:
      MINIO_ROOT_USER: minio-access-key
      MINIO_ROOT_PASSWORD: minio-secret-key
      MINIO_DEFAULT_BUCKETS: minio-bucket-name
      MINIO_UPDATE: off
      MINIO_REGION: eu-central-001
      MINIO_USE_SSL: false
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 1s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    image: ghcr.io/datageo-cz/backend
    build: ../backend
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      BASE_URL: http://localhost:3000
      DB_HOST: postgis
      DB_PASSWORD: root
      DB_USERNAME: postgres
      DB_DATABASE_NAME: postgres
      MINIO_ENDPOINT: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: false
      MINIO_REGION: eu-central-001
      MINIO_ACCESS_KEY: minio-access-key
      MINIO_SECRET_KEY: minio-secret-key
      MINIO_BUCKET_NAME: minio-bucket-name
      MINIO_PUBLIC_BUCKET_NAME: minio-public-bucket-name
      GEOLOCATION_API_URL: http://geocoding:3000
      REDIS_HOST: bullmq-redis
      REDIS_PORT: 6379
    depends_on:
      minio:
        condition: service_healthy
      postgis:
        condition: service_healthy
      bullmq-redis:
        condition: service_healthy

  geocoding:
    container_name: geocoding
    image: ghcr.io/datageo-cz/geocoding
    build: ../services/geocoding
    environment:
      NODE_ENV: production
      DB_HOST: postgis
      DB_PASSWORD: root
      DB_USERNAME: postgres
      DB_DATABASE_NAME: postgres
    depends_on:
      minio:
        condition: service_healthy
      postgis:
        condition: service_healthy

  bullmq-redis:
    container_name: bullmq-redis
    image: 'redis:alpine'
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ../.devcontainer/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    environment:
      REDIS_REPLICATION_MODE: master
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6379", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5