name: Publish SDK package

on:
    push:
        branches:
            - release

jobs:
    check-version:
        name: Test SDK version
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"

            - name: Check if the NPM version is free
              run: bash ./scripts/check-npm-version.sh

    test:
        name: Test SDK package
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"
                  cache: "npm"
                  cache-dependency-path: package-lock.json
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

            - name: Install dependencies
              run: npm ci

            - name: Test SDK
              run: npm test

    publish-sdk:
        name: Build and publish SDK package
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"
                  cache: "npm"
                  cache-dependency-path: package-lock.json
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

            - name: Publish SDK
              run: cd sdk && npm publish --ignore-scripts
